debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: jinsugyeong
    password: as0098
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true	#테스트용 데이터베이스 만들 수 있게
    hibernate.ddl-auto: create	#자동으로 ddl문 생성
    #open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true	#한줄로 나와야할 디버그 코멘트를 예쁘게
      hibernate.default_batch_fetch_size: 100	#연관관계가 맵핑된 테이블 한번에 셀렉트 문으로
  #h2.console.enabled: true
  sql.init.mode: always
  data.rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf.cache: false